# Site settings
title: "Dreckiges Gold"
email: marie.timcke@journocode.com
url: http://www.journocode.com/muell
description: "One man's trash is another man's treasure"


# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: "Journocode"

#baseurl: /campuslauf


# Team names, titles and social links
people:
- name: Marie-Louise Timcke
  pic: 1
  position:
  social:
    - title: twitter
      url: http://www.twitter.com/datentaeterin
    - title: github
      url: https://github.com/marielouiese
    - title: globe
      url: http://datentaeter.de/
